services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: biotech-api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: biotech-frontend
    depends_on:
      - api
    environment:
      API_BASE_URL: http://api:8000
    ports:
      - "8501:8501"
